services:
  db:
    container_name: db-todo
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    restart: always

  backend:
    container_name: backend-todo
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    # command: django-admin startproject core .
    # command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:7000
    ports:
      - 7000:7000
    environment:
      - DEBUG=True
    # env_file:
    #   - ./envs/dev/django/.env
    restart: always
    depends_on:
      - db